api:
  version: v1
server:
  forward-headers-strategy: framework
  servlet:
    session:
      cookie:
        secure: true
spring:
  application:
    name: givr
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google-org:
            provider: google
            client-id: 59329642408-cptukql88mom4jrs7lhkktnv235s74qd.apps.googleusercontent.com
            client-secret: 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
            scope:
              - openid
              - profile
              - email
            redirect-uri: "{baseUrl}/v1/api/organization/oauth2/code/google"
          google-volunteer:
            provider: google
            client-id: 59329642408-cptukql88mom4jrs7lhkktnv235s74qd.apps.googleusercontent.com
            client-secret: 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
            scope:
              - openid
              - profile
              - email
            redirect-uri: "{baseUrl}/v1/api/volunteer/oauth2/code/google"
givr:
  allowed:
    origins: http://localhost:5173,http://127.0.0.1:5173
springdoc:
  api-docs:
    path: api-docs
client:
  app:
    baseUrl: http://127.0.0.1:5173
jwt:
  secret: 94066f62-842d-460d-a245-1643417ff6ab
OTP:
  SECRETS: 4c57a773-965d-446c-b54f-71d24be87c12
RESEND_API_TOKEN: re_F1tc3YHH_5HicDQGBHUdFLqFgNMaVT6fd