package com.backend.givr.shared.enums;

public enum VerificationStatus {
    VERIFIED, UNVERIFIED, AUTOMATIC_VERIFICATION_FAILED, AUTOMATIC_VERIFICATION_SUCCEEDED, AUTOMATIC_VERIFICATION_PENDING, PENDING
}
